### ISSUE TITLE
Cannot find module './titanium-view'

### ISSUE THREAD

**Issue by nuno** [shodanuk/atom-alloy#1]
when I toggle the Alloy menu i got:

**Atom Version**: 0.188.0
**System**: Mac OS X 10.9.5
**Thrown From**: [atom-alloy](https://github.com/shodanuk/atom-alloy) package, v0.0.1
### Stack Trace

Failed to activate the atom-alloy package

```
At Cannot find module './titanium-view'

Error: Cannot find module './titanium-view'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/nuno/.atom/packages/atom-alloy/lib/alloy.coffee:1:16)
  at Object.<anonymous> (/Users/nuno/.atom/packages/atom-alloy/lib/alloy.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:678:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:236:14)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:741:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:223:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:157:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:73:30)
  at EventEmitter.emit (events.js:116:17)

```
### Commands

```
  4x -1:20.2 core:backspace (atom-text-editor.editor.mini)
  2x -1:15.4 editor:newline (atom-text-editor.editor)
     -1:11.8 autocomplete:toggle (atom-text-editor.editor)
     -1:08.4 core:backspace (atom-text-editor.editor)
     -1:06.8 autocomplete:toggle (atom-text-editor.editor)
 24x -1:02.5 core:undo (atom-text-editor.editor)
  2x -0:52.4 editor:newline (atom-text-editor.editor.is-focused)
     -0:48.7 autocomplete:toggle (atom-text-editor.editor.is-focused)
     -0:46.7 core:move-down (atom-text-editor.editor.mini)
     -0:45.8 core:confirm (atom-text-editor.editor.mini)
     -0:44.3 autocomplete:toggle (atom-text-editor.editor.is-focused)
 27x -0:40.8 core:move-down (atom-text-editor.editor.mini)
     -0:32.1 core:backspace (atom-text-editor.editor.mini)
     -0:12.0 autocomplete:toggle (atom-text-editor.editor.is-focused)
  2x -0:09.7 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.6 alloy:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User

# Dev
No dev packages
```

**Comment by shodanuk** [comment]
This is "fixed" however the feature throwing the error doesn't actually do anything, I'm afraid.

This project has been dead for a while as I don't use Atom at the moment.

**Comment by nuno** [comment]
@shodanuk Thanks, np.
